/*
 * An IEC 61131-3 compiler.
 *
 * Based on the
 * FINAL DRAFT - IEC 61131-3, 2nd Ed. (2001-12-10)
 *
 */


/*
 * Code to be included into the code generated by the 4th stage.
 *
 * This is part of the 4th stage that generates
 * a ST and IL source program equivalent to the IL and ST
 * code.
 * This is expected to be used mainly in debuging the syntax
 * and lexical parser, and as a starting point for other
 * 4th stages.
 */



/*
 * GENERATE_IEC.HH
 */


#ifndef _GENERATE_IEC_HH
#define _GENERATE_IEC_HH



#include <string>
#include "../../absyntax/visitor.hh"




#endif /*  _GENERATE_IEC_HH */
